export const START_PRODUCT_LIST = "START_PRODUCT_LIST";
export const SUCCESS_PRODUCT_LIST = "SUCCESS_PRODUCT_LIST";
export const ERROR_PRODUCT_LIST = "ERROR_PRODUCT_LIST";

export const START_PRODUCT_DETAIL = "START_PRODUCT_DETAIL";
export const SUCCESS_PRODUCT_DETAIL = "SUCCESS_PRODUCT_DETAIL";
export const ERROR_PRODUCT_DETAIL = "ERROR_PRODUCT_DETAIL";

export const START_CATEGORY_LIST = "START_CATEGORY_LIST";
export const SUCCESS_CATEGORY_LIST = "SUCCESS_CATEGORY_LIST";
export const ERROR_CATEGORY_LIST = "ERROR_CATEGORY_LIST";
